#!/bin/bash

git clone --recursive https://github.com/CestDiego/.emacs.d.git ~/.emacs.d

if [ -z "$(pgrep emacs)" ] ; then
    echo "Your emacs installation is valid"
    sleep 0.2
    echo "Proceding...."

else
    echo "Adding emacs ppa from cassou"
    sudo add-apt-repository ppa:cassou/emacs -y
    echo "Updating repos"
    sudo apt-get update
    echo "Installing Emacs"
    sudo apt-get install emacs24 emacs24-el emacs24-common-non-dfsg -y
fi

echo "Backing up old ~/.emacs.d as ~/.emacs.d.old"
if [ -d "~/.emacs.d" ]; then
    mv ~/.emacs.d{,.old}
fi

echo "Installing Monaco Font"
curl -kL https://raw.github.com/cstrap/monaco-font/master/install-font-ubuntu.sh | bash

echo "Installing huspell"
sudo apt-get install hunspell hunspell-en-us hunspell-eu-es -y

sudo cp /usr/share/hunspell/en_US.aff /usr/share/hunspell/english.aff
sudo cp /usr/share/hunspell/en_US.dic /usr/share/hunspell/english.dic
sudo cp /usr/share/hunspell/eu_ES.aff /usr/share/hunspell/castellano.aff
sudo cp /usr/share/hunspell/eu_ES.dic /usr/share/hunspell/castellano.dic

echo "Starting Emacs in a separate window"
emacs &

echo "Installing Python Pip and Flake 8"
sudo apt-get install python-pip python-dev -y
sudo pip install flake8 epc jedi
echo "Setting up Aliases for emacs"
if [[$SHELL = '/bin/bash']];
then
    echo 'alias ec= "emacsclient -n"' >> ~/.bashrc
    echo 'alias ecn= "emacsclient -c"' >> ~/.bashrc
    echo 'alias ect= "emacsclient -t"' >> ~/.bashrc
elif [[$SHELL = '/bin/zsh']];
then
    echo 'alias ec= "emacsclient -n"' >> ~/.zshrc
    echo 'alias ecn= "emacsclient -c"' >> ~/.zshrc
    echo 'alias ect= "emacsclient -t"' >> ~/.zshrc
fi

echo "\033[0;32m"'         __                                     __   '"\033[0m"
echo "\033[0;32m"'  ____  / /_     ____ ___  __  __   ____  _____/ /_  '"\033[0m"
echo "\033[0;32m"' / __ \/ __ \   / __ `__ \/ / / /  /_  / / ___/ __ \ '"\033[0m"
echo "\033[0;32m"'/ /_/ / / / /  / / / / / / /_/ /    / /_(__  ) / / / '"\033[0m"
echo "\033[0;32m"'\____/_/ /_/  /_/ /_/ /_/\__, /    /___/____/_/ /_/  '"\033[0m"
echo "\033[0;32m"'                        /____/                       ....is now installed!'"\033[0m"
echo "\n\n \033[0;32mPlease look over the ~/.zshrc file to select plugins, themes, and options.\033[0m"
echo "\n\n \033[0;32mp.s. Follow us at http://twitter.com/ohmyzsh.\033[0m"
echo "\n\n \033[0;32mp.p.s. Get stickers and t-shirts at http://shop.planetargon.com.\033[0m"
