#!/bin/bash

echo "Backing up old ~/.emacs.d as ~/.emacs.d.old"

mv ~/.emacs.d{,.old}

echo "\n cloning ... \n"

git clone --recursive git@github.com:CestDiego/.emacs.d.git ~/.emacs.d

if [ -z "$(pgrep emacs)" ] ; then
    echo "Your emacs installation is valid"
    sleep 0.2
    echo "Proceding...."
else
    echo "Adding emacs ppa from cassou"
    sudo add-apt-repository ppa:cassou/emacs -y
    echo "Updating repos"
    sudo apt-get update
    echo "Installing Emacs"
    sudo apt-get install emacs24 emacs24-el emacs24-common-non-dfsg -y
fi


echo "Installing Monaco Font"
curl -kL https://raw.github.com/cstrap/monaco-font/master/install-font-ubuntu.sh | bash

echo "Installing huspell"
sudo apt-get install hunspell hunspell-en-us hunspell-eu-es -y

sudo cp /usr/share/hunspell/en_US.aff /usr/share/hunspell/english.aff
sudo cp /usr/share/hunspell/en_US.dic /usr/share/hunspell/english.dic
sudo cp /usr/share/hunspell/eu_ES.aff /usr/share/hunspell/castellano.aff
sudo cp /usr/share/hunspell/eu_ES.dic /usr/share/hunspell/castellano.dic

echo "Starting Emacs in a separate window"
emacs &

echo "Installing Python Pip and Flake 8"
sudo apt-get install python-pip python-dev -y
sudo pip install flake8 epc jedi
echo "Setting up Aliases for emacs"
if [$SHELL = '/bin/bash'];
then
    echo 'alias ec= "emacsclient -n"' >> ~/.bashrc
    echo 'alias ecn= "emacsclient -c"' >> ~/.bashrc
    echo 'alias ect= "emacsclient -t"' >> ~/.bashrc
elif [$SHELL = '/bin/zsh'];
then
    echo 'alias ec= "emacsclient -n"' >> ~/.zshrc
    echo 'alias ecn= "emacsclient -c"' >> ~/.zshrc
    echo 'alias ect= "emacsclient -t"' >> ~/.zshrc
fi

echo "Setting up the ecn for the emacsclient"

sudo cp ~/.emacs.d/initial-scripts/ecn /usr/local/bin/ecn


echo "#######################################################################"
echo "     /  /\         /__/\         /  /\         /  /\         /  /\   "
echo "    /  /:/_       |  |::\       /  /::\       /  /:/        /  /:/_   "
echo "   /  /:/ /\      |  |:|:\     /  /:/\:\     /  /:/        /  /:/ /\  "
echo "  /  /:/ /:/_   __|__|:|\:\   /  /:/~/::\   /  /:/  ___   /  /:/ /::\ "
echo " /__/:/ /:/ /\ /__/::::| \:\ /__/:/ /:/\:\ /__/:/  /  /\ /__/:/ /:/\:\ "
echo " \  \:\/:/ /:/ \  \:\~~\__\/ \  \:\/:/__\/ \  \:\ /  /:/ \  \:\/:/~/:/ "
echo "  \  \::/ /:/   \  \:\        \  \::/       \  \:\  /:/   \  \::/ /:/ "
echo "   \  \:\/:/     \  \:\        \  \:\        \  \:\/:/     \__\/ /:/  "
echo "    \  \::/       \  \:\        \  \:\        \  \::/        /__/:/   "
echo "     \__\/         \__\/         \__\/         \__\/         \__\/    "
echo "#######################################################################"
echo " "
echo "Thanks for trying Hackspace Emacs Configuration, got to github.com/cestdiego/.emacs.d"
echo "for details or just see the README.org (obviously with your freshly installed emacs)"
echo "Just do a M-x find-file RET ~/.emacs.d/README.org RET"
